### ISSUE TITLE
1._ Como atleta puedo acceder al landing page de la pagina para registrarme e iniciar sesión

### ISSUE THREAD

**Issue by ParraJuanPablo** [ParraJuanPablo/Get-Fit#1]
-Debe tener un nav bar.
-Debe tener un footer.
-Debe tener un mensaje de bienvenida con imagen.
-Debe tener un botón para registrarme.
-Debe tener un botón para iniciar sesión.

**Comment by bryanstgarcia** [comment]
![Image](https://user-images.githubusercontent.com/30266134/228694983-d03d776c-5d88-4c4a-8ebf-9efe4899025b.png)



![Image](https://user-images.githubusercontent.com/30266134/228694876-f60e71ad-1c13-454c-8aab-a470a2947b46.png)




![Image](https://user-images.githubusercontent.com/30266134/228695013-390864a4-0c71-482f-be68-5e16be0792a6.png)

**Comment by bryanstgarcia** [comment]
```
<style>
  @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap');
</style>
```
